---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    name: kafka
    layer: messaging
---
apiVersion: v1
kind: Namespace
metadata:
  name: spark
  labels:
    name: spark
    layer: processing
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
    layer: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    name: analytics
    layer: query
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    layer: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-generator
  labels:
    name: data-generator
    layer: ingestion
